spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/promotion?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: promotion
    password: 'Qwer!234'
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 2
    connectionTestQuery: SELECT 1
    data-source-properties: 
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  devtools:
    livereload:
      enabled: true
  restart:
    enabled: true
  profiles:
    include: oauth

server:  
  port: ${PORT:8080}

# Mybatis
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true